In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np

In [2]:
df = pd.read_csv("fuelconsumption2021.csv")

In [3]:
df.head(9)

Model        Make              Model.1     Vehicle  Engine  Cylinders  \
0   2021       Acura                  ILX     Compact     2.4          4   
1   2021       Acura                  NSX  Two-seater     3.5          6   
2   2021       Acura           RDX SH-AWD  SUV: Small     2.0          4   
3   2021       Acura    RDX SH-AWD A-SPEC  SUV: Small     2.0          4   
4   2021       Acura           TLX SH-AWD     Compact     2.0          4   
5   2021       Acura    TLX SH-AWD A-SPEC     Compact     2.0          4   
6   2021  Alfa Romeo               Giulia    Mid-size     2.0          4   
7   2021  Alfa Romeo           Giulia AWD    Mid-size     2.0          4   
8   2021  Alfa Romeo  Giulia Quadrifoglio    Mid-size     2.9          6   

  Transmission Fueltype  FuelConsumption_city  FuelConsumption_Hwy  \
0          AM8        Z                   9.9                  7.0   
1          AM9        Z                  11.1                 10.8   
2         AS10        Z                  11.0                  8.6   
3         AS10        Z                  11.3                  9.1   
4         AS10        Z                  11.2                  8.0   
5         AS10        Z                  11.3                  8.1   
6           A8        Z                  10.0                  7.2   
7           A8        Z                  10.5                  7.7   
8           A8        Z                  13.5                  9.3   

   FuelConsumption_Comb  Unnamed: 11  Emissions  CO2rating  Smograting  
0                   8.6           33        199          6           3  
1                  11.0           26        256          4           3  
2                   9.9           29        232          5           6  
3                  10.3           27        242          5           6  
4                   9.8           29        230          5           7  
5                   9.8           29        231          5           7  
6                   8.7           32        205          6           3  
7                   9.2           31        217          5           3  
8                  11.6           24        271          4           3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876 entries, 0 to 875
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Model                 876 non-null    int64  
 1   Make                  876 non-null    object 
 2   Model.1               876 non-null    object 
 3   Vehicle               876 non-null    object 
 4   Engine                876 non-null    float64
 5   Cylinders             876 non-null    int64  
 6   Transmission          876 non-null    object 
 7   Fueltype              876 non-null    object 
 8   FuelConsumption_city  876 non-null    float64
 9   FuelConsumption_Hwy   876 non-null    float64
 10  FuelConsumption_Comb  876 non-null    float64
 11  Unnamed: 11           876 non-null    int64  
 12  Emissions             876 non-null    int64  
 13  CO2rating             876 non-null    int64  
 14  Smograting            876 non-null    int64  
dtypes: float64(4), int64(6)

In [5]:
cdf=df[['Engine','Cylinders','FuelConsumption_Comb','Emissions']]

In [6]:
y=cdf['Emissions']
x=cdf.drop(columns='Emissions')

In [7]:
y

0      199
1      256
2      232
3      242
4      230
      ... 
871    219
872    230
873    240
874    236
875    245
Name: Emissions, Length: 876, dtype: int64

In [8]:
from sklearn import linear_model
from sklearn import metrics
from sklearn import preprocessing
from sklearn import compose
from sklearn import pipeline

In [9]:
from sklearn import model_selection

In [10]:
trainx,testx,trainy,test=model_selection.train_test_split(x,y,train_size=0.8,random_state=553)

In [11]:
ohe=preprocessing.OneHotEncoder()

In [12]:
ohe.fit(x[['Engine','Cylinders','FuelConsumption_Comb']])

OneHotEncoder()

In [13]:
ohe.categories_

[array([1. , 1.2, 1.3, 1.4, 1.5, 1.6, 1.8, 2. , 2.3, 2.4, 2.5, 2.7, 2.8,
        2.9, 3. , 3.2, 3.3, 3.5, 3.6, 3.7, 3.8, 4. , 4.3, 4.4, 4.6, 5. ,
        5.2, 5.3, 5.6, 5.7, 6. , 6.2, 6.4, 6.5, 6.6, 6.7, 8. ]),
 array([ 3,  4,  5,  6,  8, 10, 12, 16], dtype=int64),
 array([ 4. ,  4.2,  4.4,  4.5,  4.6,  4.8,  4.9,  5. ,  5.1,  5.3,  5.5,
         5.6,  5.8,  5.9,  6. ,  6.1,  6.2,  6.4,  6.5,  6.7,  6.9,  7. ,
         7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,
         8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,
         9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3,
        10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1, 11.2, 11.3, 11.4,
        11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3, 12.4, 12.5,
        12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2, 13.3, 13.4, 13.5, 13.6,
        13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7,
        14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4, 15.6, 15.7, 15.9, 

In [14]:
column_trans=compose.make_column_transformer((preprocessing.OneHotEncoder(categories=ohe.categories_),['Engine','Cylinders','FuelConsumption_Comb']),remainder='passthrough')


In [15]:
print(column_trans)

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array([1. , 1.2, 1.3, 1.4, 1.5, 1.6, 1.8, 2. , 2.3, 2.4, 2.5, 2.7, 2.8,
       2.9, 3. , 3.2, 3.3, 3.5, 3.6, 3.7, 3.8, 4. , 4.3, 4.4, 4.6, 5. ,
       5.2, 5.3, 5.6, 5.7, 6. , 6.2, 6.4, 6.5, 6.6, 6.7, 8. ]),
                                                           array([ 3,  4,  5,  6,  8, 10, 12, 16], dtype=int64),
                                                           array([ 4. ,  4.2,  4.4,  4.5,  4.6,  4.8,  4.9,  5. ,  5.1,  5.3,  5.5,
        5.6,  5.8,  5.9,...
       11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3, 12.4, 12.5,
       12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2, 13.3, 13.4, 13.5, 13.6,
       13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7,
       14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4, 15.6, 15.7, 15.9, 16. ,
       16.3, 16.4, 16.5, 16.6, 16.7, 16.9, 17.4, 17.6, 17.7, 18.3, 19. ,
  

In [16]:
lr=linear_model.LinearRegression()

In [17]:
pipe=pipeline.make_pipeline(column_trans,lr)

In [18]:
pipe.fit(trainx,trainy)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([1. , 1.2, 1.3, 1.4, 1.5, 1.6, 1.8, 2. , 2.3, 2.4, 2.5, 2.7, 2.8,
       2.9, 3. , 3.2, 3.3, 3.5, 3.6, 3.7, 3.8, 4. , 4.3, 4.4, 4.6, 5. ,
       5.2, 5.3, 5.6, 5.7, 6. , 6.2, 6.4, 6.5, 6.6, 6.7, 8. ]),
                                                                            array([ 3,  4,  5,  6,  8, 10, 12, 16], dtype=int64),
                                                                            array([ 4. ,  4.2,  4.4,  4.5,  4....
       11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1, 12.2, 12.3, 12.4, 12.5,
       12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2, 13.3, 13.4, 13.5, 13.6,
       13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7,
       14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4, 15.6, 15.7, 15.9, 16. ,
       16.3, 16

In [19]:
pipe.predict(testx)

array([139.17460194, 248.16675433, 367.3044226 , 287.0311453 ,
       340.3532741 , 177.06917614, 321.5134927 , 368.7518301 ,
       217.2585734 , 273.51088964, 258.7648416 , 235.87968961,
       226.4158422 , 289.47398045, 116.99999446, 260.26609439,
       319.52441027, 278.27133441, 227.14291293, 297.85801905,
       279.07793796, 252.55249593, 279.07793796, 237.54205623,
       368.7518301 , 283.56905787, 252.55249593, 224.05295462,
       258.28626541, 303.2523046 , 275.47042146, 325.54125569,
       235.87968961, 184.95691796, 195.21693216, 194.3915375 ,
       268.82270884, 207.02526476, 311.1633571 , 311.1633571 ,
       242.45025286, 247.02318886, 164.16899493, 305.16246244,
       244.99796264, 275.86921061, 331.40436806, 274.56582548,
       290.35785263, 275.47042146, 274.84033066, 351.98858107,
       278.27133441, 318.90901273, 340.3532741 , 213.92482752,
       243.76407691, 262.9875163 , 349.09865618, 124.836608  ,
       258.60177471, 212.39320293, 321.61795776, 273.37

In [20]:
metrics.r2_score(test,pipe.predict(testx))

0.9854146971002757

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876 entries, 0 to 875
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Model                 876 non-null    int64  
 1   Make                  876 non-null    object 
 2   Model.1               876 non-null    object 
 3   Vehicle               876 non-null    object 
 4   Engine                876 non-null    float64
 5   Cylinders             876 non-null    int64  
 6   Transmission          876 non-null    object 
 7   Fueltype              876 non-null    object 
 8   FuelConsumption_city  876 non-null    float64
 9   FuelConsumption_Hwy   876 non-null    float64
 10  FuelConsumption_Comb  876 non-null    float64
 11  Unnamed: 11           876 non-null    int64  
 12  Emissions             876 non-null    int64  
 13  CO2rating             876 non-null    int64  
 14  Smograting            876 non-null    int64  
dtypes: float64(4), int64(6)

In [25]:
# pipe.predict(pd.DataFrame([[4,8,15.8]],columns=['Engine','Cylinders','FuelConsumption_Comb']))
pipe.predict(pd.DataFrame([[4,8,15,]],columns=['Engine','Cylinders','FuelConsumption_Comb']))

array([347.38321127])